version: '3.0'
services:
    trafficserver:
        build:
            context: .
            args: 
                ats_version: latest
        image: trafficserver
        container_name: trafficserver
        restart: unless-stopped
        ports:
            - "12080:80"
            - "12443:443"
        environment:
            - STORAGE=/cache1:-10G /cache2:-10G
            - REMAP=ts.local:-127.0.0.1
