version: '3.0'
services:
    trafficserver:
        build:
            context: .
        image: trafficserver:8.0.5
        container_name: trafficserver
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        environment:
            - STORAGE=/cache1:-10G /cache2:-10G
            - REMAP=orange1.org:-192.168.122.120 orange2.org:-192.168.122.172
